<?php

/**
 * Created by PhpStorm.
 * User: gary
 * Date: 2017/11/8
 * Time: 18:30
 */
namespace App\Libraries;

class CacheKey
{
    const TAB_BAR_CATEGORIES = 'API:TAB_BAR_CATEGORIES';
    const SALES_PRODUCT_LIST = 'API:SALES_PRODUCT_LIST';

    const HOME_PRODUCT_LIST = 'API:HOME_PRODUCT_LIST:PAGE:';
    const HOME_BANNER_LIST = 'API:HOME_BANNER:LAYOUT:';
    const HOME_KEYWORD_LIST = 'API:HOME_KEYWORD_LIST';

    const CATEGORIES_LIST_PRODUCT = 'API:CATEGORIES_LIST_PRODUCT:ID:';

    const PRODUCT_DETAIL = 'API:PRODUCT_DETAIL:ID:';

    const WECHAT_SESSION = 'API:WECHAT:SESSION:';

    const USER_INFO = 'API:USER_INFO:ID:';

}